services:
  # Servicio de microservice-config
  - type: web
    name: microservice-config
    runtime: docker
    dockerfilePath: ./microservicios-integrados-BackenEnd/microservice-config/Dockerfile
    envVars:
      - key: "ENVIRONMENT"
        value: "production"
      - key: PORT
        value: 8888     

  # Servicio de micro-service-eureka
  - type: web
    name: micro-service-eureka
    runtime: docker
    dockerfilePath: ./microservicios-integrados-BackenEnd/microservice-eureka/Dockerfile
    envVars:
      - key: "ENVIRONMENT"
        value: "production"
      - key: PORT
        value: 8761

  # Servicio micro-service-api-getewa (API Gateway)
  - type: web
    name: micro-service-api-getewa
    runtime: docker
    dockerfilePath: ./microservicios-integrados-BackenEnd/microservice-gateway/Dockerfile
    envVars:
      - key: "ENVIRONMENT"
        value: "production"
      - key: PORT
        value: 8080

  # Servicio micro-service-auth (Autenticación)
  - type: web
    name: micro-service-auth
    runtime: docker
    dockerfilePath: ./microservicios-integrados-BackenEnd/microservice-auth/Dockerfile
    envVars:
      - key: "ENVIRONMENT"
        value: "production"
      - key: PORT
        value: 8092

  # Servicio micro-service-student (Estudiantes)
  - type: web
    name: micro-service-student
    runtime: docker
    dockerfilePath: ./microservicios-integrados-BackenEnd/microservice-student/Dockerfile
    envVars:
      - key: "ENVIRONMENT"
        value: "production"
      - key: PORT
        value: 8090

  # Servicio micro-service-course (Cursos)
  - type: web
    name: micro-service-course
    runtime: docker
    dockerfilePath: ./microservicios-integrados-BackenEnd/microservice-course/Dockerfile
    envVars:
      - key: "ENVIRONMENT"
        value: "production"
      - key: PORT
        value: 9090

  # Servicio micro-service-report (Reportes)
  - type: web
    name: micro-service-report
    runtime: docker
    dockerfilePath: ./microservicios-integrados-BackenEnd/microservice-report/Dockerfile
    envVars:
      - key: "ENVIRONMENT"
        value: "production"
      - key: PORT
        value: 8091

