server:
  port: 8761

spring:
  application:
    name: micro-service-eureka

eureka:
  instance:
    hostname: web-microservicios-eureka-c2etd5a9ezgggsdy.centralus-01.azurewebsites.net
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: false
  client:
    fetch-registry: false
    register-with-eureka: false
    defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/