server:
  port: 9090

spring:
  application:
    name: micro-service-course
  datasource:
    url: jdbc:sqlserver://servidor-microservios.database.windows.net:1433;databaseName=microservicios_DB;
    username: admin-microservicios
    password: Carta87.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10  # Ajusta este valor según la cantidad de conexiones simultáneas
  jpa:
    hibernate:
      ddl-auto: update
    database: sqlserver
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: https://web-microservicios-eureka-c2etd5a9ezgggsdy.centralus-01.azurewebsites.net/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: TRACE

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
  cache:
    disabled: true