server:
  port: 8092
  forward-headers-strategy: framework

jw:
  secret:
    key: 586E3272357538782F413F4428472B4B6250655368566B597033733676397924
  time:
    expiration: 3600000 # una hora

spring:
  application:
    name: micro-service-auth
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cslbd33qf0us738qqojg-a.virginia-postgres.render.com:5432/proyecto_microservices_sav8
    username: root
    password: jbhvUvQaX9AkFGKiOXYxE2Ak339ghjhS
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: https://microservice-eureka-v1.onrender.com/eureka

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
  cache:
    disabled: true