server:
  port: 8091

spring:
  application:
    name: micro-service-report
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_container_DB:3306/micro_services
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://micro-service-eureka:8761/eureka