spring:
  application:
    name: micro-service-student
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cslbd33qf0us738qqojg-a.virginia-postgres.render.com:5432/proyecto_microservices_sav8
    username: root
    password: jbhvUvQaX9AkFGKiOXYxE2Ak339ghjhS
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: https://microservice-eureka-v1.onrender.com/eureka