version: "3.9"

networks:
  microservices_network:
    external: true
    name: microservicios-integrados-backenend_microservices_network
services:
  microservice-config:
    image: microservice-config-image:latest
    container_name: microservice-config
    build: ./microservice-config
    expose:
      - "8888"
    ports:
      - "8888:8888"
    networks:
      - microservices_network

  mysql_container:
    image: mysql
    container_name: mysql_container_DB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: micro_services
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_container-volume:/var/lib/mysql
    expose:
      - "13306"
    ports:
      - "13306:3306"
    networks:
      - microservices_network

  postgrest_container:
    image: postgres
    container_name: postgrest_container_DB
    environment:
      POSTGRES_DB: coursesDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres-dataDB:/data/postgres
    expose:
      - "5435"
    ports:
      - "5435:5432"
    networks:
      - microservices_network

  micro-service-eureka:
    image: microservice-eureka-image:latest
    container_name: micro-service-eureka
    build: ./microservice-eureka
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      - microservices_network
    depends_on:
      - microservice-config

  micro-service-api-getewa:
    image: microservice-gateway-image:latest
    container_name: micro-service-api-getewa
    build: ./microservice-gateway
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - microservices_network
    depends_on:
      - microservice-config
      - micro-service-eureka

  microservice-auth:
    image: microservice-auth-image:latest
    container_name: microservice-auth
    build: ./microservice-auth
    ports:
      - "8092:8092"
    networks:
      - microservices_network
    depends_on:
      - microservice-config
      - micro-service-eureka
      - micro-service-api-getewa
      - mysql_container

  micro-service-report:
    image: microservice-report-image:latest
    container_name: micro-service-report
    build: ./microservice-report
    expose:
      - "8091"
    ports:
      - "8091:8091"
    networks:
      - microservices_network
    depends_on:
      - microservice-config
      - micro-service-eureka
      - micro-service-api-getewa
      - mysql_container

  micro-service-student:
    image: microservice-student-image:latest
    container_name: micro-service-student
    build: ./microservice-student
    expose:
      - "8090"
    ports:
      - "8090:8090"
    networks:
      - microservices_network
    depends_on:
      - microservice-config
      - micro-service-eureka
      - micro-service-api-getewa
      - mysql_container

  microservice-course:
    image: microservice-course-image:latest
    container_name: microservice-course
    build: ./microservice-course
    ports:
      - "9090:9090"
    networks:
      - microservices_network
    depends_on:
      - microservice-config
      - micro-service-eureka
      - micro-service-api-getewa
      - postgrest_container
      - micro-service-student

volumes:
  mysql_container-volume:
    driver: local
